### ISSUE TITLE
decode-stream-header not working

### ISSUE THREAD

**Issue by japonophile** [clj-commons/gloss#48]
When trying to use decode-stream-header, I get the following exception:

```
IllegalArgumentException cannot convert clojure.lang.PersistentArrayMap to sink  manifold.stream/->sink (stream.clj:70)
user=> (.printStackTrace *e)
java.lang.IllegalArgumentException: cannot convert clojure.lang.PersistentArrayMap to sink, compiling:(NO_SOURCE_FILE:1:8)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3628)
    at clojure.lang.Compiler$DefExpr.eval(Compiler.java:439)
    at clojure.lang.Compiler.eval(Compiler.java:6787)
    at clojure.lang.Compiler.eval(Compiler.java:6745)
    at clojure.core$eval.invoke(core.clj:3081)
    at clojure.main$repl$read_eval_print__7099$fn__7102.invoke(main.clj:240)
    at clojure.main$repl$read_eval_print__7099.invoke(main.clj:240)
    at clojure.main$repl$fn__7108.invoke(main.clj:258)
    at clojure.main$repl.doInvoke(main.clj:258)
    at clojure.lang.RestFn.invoke(RestFn.java:1096)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__608.invoke(interruptible_eval.clj:43)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invoke(core.clj:630)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:41)
    at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__649$fn__652.invoke(interruptible_eval.clj:171)
    at clojure.core$comp$fn__4495.invoke(core.clj:2437)
    at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__642.invoke(interruptible_eval.clj:138)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: cannot convert clojure.lang.PersistentArrayMap to sink
    at manifold.stream$__GT_sink.invoke(stream.clj:70)
    at manifold.stream$connect_via.invoke(stream.clj:494)
    at manifold.stream$connect_via.invoke(stream.clj:492)
    at gloss.io$decode_stream_headers.doInvoke(io.clj:185)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at asimov.tcpros$subscribe_BANG_$fn__1263.invoke(tcpros.clj:71)
    at manifold.deferred$fn__7431$chain___7452.invoke(deferred.clj:840)
    at asimov.tcpros$subscribe_BANG_.invoke(tcpros.clj:71)
    at asimov.api$sub_BANG_$iter__86__90$fn__91$fn__92.invoke(api.clj:95)
    at asimov.api$sub_BANG_$iter__86__90$fn__91.invoke(api.clj:85)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.RT.seq(RT.java:507)
    at clojure.core$seq__4128.invoke(core.clj:137)
    at asimov.api$sub_BANG_.invoke(api.clj:99)
    at clojure.lang.AFn.applyToHelper(AFn.java:160)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3623)
    ... 23 more
nil
```

**Comment by KingMob** [comment]
Closed by #49
